version: '3.1'

services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway
    restart: always
    ports:
      - 8080:8080
    networks:
      - overlay

  service-auth:
    container_name: service-auth
    build:
      context: ./authentication
    restart: always
    networks:
      - overlay

  service-profile:
    container_name: service-profile
    build:
      context: ./profile
    restart: always
    networks:
      - overlay

  service-tweets:
    container_name: service-tweet
    build:
      context: ./tweet
    restart: always
    networks:
      - overlay

networks:
  overlay:
